# Linear algebra: Matrix operations

## Libraries

To check every exercise here, import all libraries first, and then, run all codes below

In [49]:
import numpy as np
import torch as pt
import tensorflow as tf

---

## Eigenvectors and eigenvalues

Eigenvectors is a special vector $v$ such that when it is transformed by some matrix, the product $Av$ has the same direction as $v$.

An eigenvalue is a scalar (traditionally represented as $\lambda$) that simply scales the eigenvector $v$ such that the following equation is satisfied:

$$Av = \lambda v$$

> This topic applies only to square matrices, though in linear algebra we have singular value decomposition (SVD) which uses singular values and singular vectors and can be used in non-square matrices.

### Numpy

In [50]:
A = np.array([[4, 1], [2, 3]])
A

array([[4, 1],
       [2, 3]])

In [51]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Eigenvalues {eigenvalues}")
print(f"Eigenvectors {eigenvectors}")

Eigenvalues [5. 2.]
Eigenvectors [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


---

### PyTorch

In [52]:
B = pt.tensor([[4, 1], [2, 3]], dtype=pt.float32)
B

tensor([[4., 1.],
        [2., 3.]])

In [53]:
eigenvalues, eigenvectors = pt.linalg.eig(B)
print(f"Eigenvalues {eigenvalues}")
print(f"Eigenvectors {eigenvectors}")

Eigenvalues tensor([5.+0.j, 2.+0.j])
Eigenvectors tensor([[ 0.7071+0.j, -0.4472+0.j],
        [ 0.7071+0.j,  0.8944+0.j]])


### Tensorflow

In [54]:
C = tf.Variable([[4, 1], [2, 3]], dtype=tf.float32)
C

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[4., 1.],
       [2., 3.]], dtype=float32)>

In [55]:
eigenvalues, eigenvectors = tf.linalg.eig(C)
print(f"Eigenvalues {eigenvalues}")
print(f"Eigenvectors {eigenvectors}")

Eigenvalues [4.9999995+0.j 1.9999999+0.j]
Eigenvectors [[ 0.70710677+0.j -0.4472136 +0.j]
 [ 0.70710677+0.j  0.89442724+0.j]]


> In PyTorch and TensorFlow if you use `torch.linalg.eig` you can get complex values. If the matrix is symmetric you can also use `torch.linalg.eigh` to get real eigenvalues.

---

## Matrices determinants

Matrix determinants A matrix determinant is a scalar value that can map a square matrix into it 
- Enable us to determine whether the matrix can be inverted. 
- It is denoted by:
$$ det(X) $$

If $det(X) = 0$:
- Matrix $X^{-1}$ can't be computed because: $X^{-1}$ has $1/det(X) = 1/0$
- Matrix $X$ is singular: It contains linearly dependent columns.

### Numpy

In [56]:
A = np.array([[4, 2], [-5 , -3]])
A

array([[ 4,  2],
       [-5, -3]])

In [57]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

### PyTorch

In [58]:
B = pt.tensor([[4, 2], [-5 , -3]], dtype=pt.float32) # PyTorch and TensorFlow need to be float values to work with
B

tensor([[ 4.,  2.],
        [-5., -3.]])

In [59]:
pt.linalg.det(B)

tensor(-2.)

### TensorFlow

In [60]:
C = tf.Variable([[4, 2], [-5, -3]], dtype=tf.float32)
C

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 4.,  2.],
       [-5., -3.]], dtype=float32)>

In [61]:
tf.linalg.det(C)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.000000476837158>

---

## Determinants and eigenvalues

The determinant of a matrix is the product of all eigenvalues of the matrix. 

$$det(X) = \prod \lambda v$$

The determinant quantifies volume change as a result of applying X:
- If $|det(X)| = 0$, then $X$ collapses space completely in at least one dimension, thereby eliminating all volume.
- If $0 < |det(X)| < 1$, then $X$ contracts volume to some extent.
- If $|det(X)| = 1$, then $X$ preserves volume exactly.
- If |$det(X)| > 1$, then X expands volume.

---

## Eigendescomposition

Having a square matrix A n x n, then eigendecomposition is denoted by:

$$A = V \Lambda V^{-1}$$

Where:
- $V$ is a square matrix **n x n** where its columns are the eigenvectors of $A$.
- $\Lambda$ is a diagonal matrix **n x n** whose elements are the eigenvalues of $A$.
- $V^{-1}$ is the inverse of $V$ always $V$ has inversion.

In [62]:
V = pt.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4]], dtype=pt.float32) # Original matrix
V

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [63]:
eigenvalues, eigenvectors = pt.linalg.eig(V) # Eigenvalues and eigenvectors
print(f"Eigenvalues {eigenvalues}")
print(f"Eigenvectors {eigenvectors}")

Eigenvalues tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j])
Eigenvectors tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
        [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
        [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]])


In [64]:
diag = pt.diag(eigenvalues) # Diagonal matrix of eigenvalues
diag

tensor([[23.7644+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  6.6684+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -3.4328+0.j]])

In [65]:
original_V = eigenvectors @ diag @ pt.linalg.inv(eigenvectors) # Reconstruct original matrix
original_V

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 3.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [ 5.0000+0.j,  7.0000+0.j,  4.0000+0.j]])