# Linear algebra: Matrix Operations

## Libraries

To check every exercise here, import all libraries first, and then, run all codes below

In [1]:
import numpy as np
import torch as pt
import tensorflow as tf

---

## Forbenius Norm

Frobenius norm is analogous to the L2 norm vector because both of them measure the size of matrices and vectors respectively in terms of Euclidean distance
- It's the sum of the magnitude of all the vectors in <strong>*X*</strong>
- Described by:
$$
    \left\| X \right\|_{F} = \sqrt{\sum_{i,j} x^{2}_{i,j}}
$$

In [10]:
X = pt.tensor([[1, 2], [3, 4]], dtype=pt.float32) # Tensorflow and PyTorch requieres floats to work

In [8]:
pt.norm(X) # Default norm is L2

tensor(5.4772)

---

## Matrix Multiplication

The matrix multiplication is an operation with one important rule:

- Having matrices A and B, the columns and rows between them need to be equal

The formula to describes matrix multiplication is:
$$
C_{i,k} = \sum_{j}A_{i,j}B_{j,k}
$$

> Note that matrix multiplications in not "commutative" (i.e., $AB \neq BA$)

### Matrix multiplication (with a vector)

#### Numpy

In [3]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [5]:
v1 = np.array([1,2])
v1

array([1, 2])

In [7]:
np.dot(A, v1) # Numpy use dot product for matrix-vector multiplication though it is not the same as the dot product of two vectors

array([11, 17, 23])

---

#### PyTorch

In [9]:
B = pt.tensor([[3, 4], [5, 6], [7, 8]], dtype=pt.float32) # Tensorflow and PyTorch requieres floats to work
B

tensor([[3., 4.],
        [5., 6.],
        [7., 8.]])

In [10]:
C = pt.tensor([1, 2], dtype=pt.float32)
C

tensor([1., 2.])

In [11]:
pt.matmul(B, C) # PyTorch use matmul for matrix-vector multiplication

tensor([11., 17., 23.])

> Like numpy.dot(), matmul function in PyTorch infers dims in order to perform dot product, matvec or matrix multiplication

---

#### Tensorflow

In [12]:
D = tf.Variable([[3, 4], [5, 6], [7, 8]], dtype=tf.float32) # Tensorflow and PyTorch requieres floats to work
D

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[3., 4.],
       [5., 6.],
       [7., 8.]], dtype=float32)>

In [14]:
E = tf.Variable([1, 2], dtype=tf.float32)
E

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [17]:
tf.linalg.matvec(D, E) # Tensorflow needs to be explicit about the type of multiplication

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([11., 17., 23.], dtype=float32)>

---

### Matrix multiplication (with matrices)

#### Numpy

In [20]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [28]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [31]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

---

#### PyTorch

In [33]:
C = pt.tensor([[3, 4], [5, 6], [7, 8]], dtype=pt.float32) # Tensorflow and PyTorch requieres floats to work
C

tensor([[3., 4.],
        [5., 6.],
        [7., 8.]])

In [34]:
D = pt.tensor([[1, 9], [2, 0]], dtype=pt.float32)
D

tensor([[1., 9.],
        [2., 0.]])

In [35]:
pt.matmul(C, D)

tensor([[11., 27.],
        [17., 45.],
        [23., 63.]])

---

#### Tensorflow

In [37]:
E = tf.Variable([[3, 4], [5, 6], [7, 8]], dtype=tf.float32) # Tensorflow and PyTorch requieres floats to work
E

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[3., 4.],
       [5., 6.],
       [7., 8.]], dtype=float32)>

In [38]:
F = tf.Variable([[1, 9], [2, 0]], dtype=tf.float32)
F

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 9.],
       [2., 0.]], dtype=float32)>

In [39]:
tf.linalg.matmul(E, F)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 27.],
       [17., 45.],
       [23., 63.]], dtype=float32)>