# Linear algebra: Tensor operations

## Libraries

To check every exercise here, import all libraries first, and then, run all codes below:

In [1]:
import torch as pt

---

## Tensor transposition

Tensor transposition is the action of changing the rows and columns over the main diagonal of a matrix.

$$
(X^{T})_{i,j} = X_{j,i}
$$

In [2]:
# Matrix declaration
X = pt.tensor([[25,2], [5, 26], [3, 7]])
X

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [3]:
# Matrix tranposition
X.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

---

## Basic Tensor arithmetic operations

Adding or multiplying with scalars applies the operation to all elements in the matrix and its shape is retained.

In [4]:
# Addition
X + 3

tensor([[28,  5],
        [ 8, 29],
        [ 6, 10]])

In [5]:
# Subtraction
X - 5

tensor([[20, -3],
        [ 0, 21],
        [-2,  2]])

In [6]:
# Multiplication
X * 2

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [7]:
# Division
X / 2

tensor([[12.5000,  1.0000],
        [ 2.5000, 13.0000],
        [ 1.5000,  3.5000]])

In PyTorch, you can use embedded functions to make arithmetic operations

In [8]:
print(f"Addition: {pt.add(X, 3)}")
print(f"Subtraction: {pt.sub(X, 5)}")
print(f"Multiplication: {pt.mul(X, 2)}")
print(f"Division: {pt.div(X, 2)}")

Addition: tensor([[28,  5],
        [ 8, 29],
        [ 6, 10]])
Subtraction: tensor([[20, -3],
        [ 0, 21],
        [-2,  2]])
Multiplication: tensor([[50,  4],
        [10, 52],
        [ 6, 14]])
Division: tensor([[12.5000,  1.0000],
        [ 2.5000, 13.0000],
        [ 1.5000,  3.5000]])


---

## Hadamard product

The Hadamard or element-wise product occurs when two matrices with the same shape apply addition or multiplication operations, it denotes the "odot" symbol.
$$
A \odot X
$$
Every element operates with the element in the other matrix in the same position.

In [9]:
A = pt.tensor([[1, 2], [3, 4]])
X = pt.tensor([[5, 6], [7, 8]])

In [10]:
A + X

tensor([[ 6,  8],
        [10, 12]])

In [11]:
A * X

tensor([[ 5, 12],
        [21, 32]])

---

## Tensor reduction

Calculating the sum across all elements of a tensor is a common operation. For example
- For vector **x** of length *n*, we calculate $\sum^{n}_{i=1}x_i$
- for matrix **X** with *m* by *n* dimensions, we calculate $\sum^{m}_{i=1}\sum^{n}_{i=1}X_{i,j}$

In [12]:
# Vector
x = pt.tensor([1, 2, 3])
print(x)
# Matrix
X = pt.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(X)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [13]:
# Vector reduction
x.sum()

tensor(6)

In [14]:
# Matrix reduction
X.sum()

tensor(45)

If only want to reduce the matrix in one dimension, we can select which to reduce, a row or a column

In [15]:
# Reduction along columns (axis 0)
X.sum(axis=0)

tensor([12, 15, 18])

In [16]:
# Reduction along rows (axis 1)
X.sum(axis=1)

tensor([ 6, 15, 24])

---

## Operations along matrices

Other operations can be applied with reduction along all or a selection of axes, e.g.:
- Maximun
- Minimu
- Mean
- Product

In [17]:
# Maximum operation
print(X.max()) # Maximum value in the matrix
print(X.max(axis=0)) # Maximum value in each column
print(X.max(axis=1)) # Maximum value in each row

tensor(9)
torch.return_types.max(
values=tensor([7, 8, 9]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([3, 6, 9]),
indices=tensor([2, 2, 2]))


In [18]:
# Minimum operation
print(X.min()) # Maximum value in the matrix
print(X.min(axis=0)) # Maximum value in each column
print(X.min(axis=1)) # Maximum value in each row

tensor(1)
torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))
torch.return_types.min(
values=tensor([1, 4, 7]),
indices=tensor([0, 0, 0]))


In [19]:
# Mean operation

# Mean function in PyTorch works with float or complex values
print(pt.mean(X, dtype=pt.float32))
print(pt.mean(X, axis=0, dtype=pt.float32))
print(pt.mean(X, axis=1, dtype=pt.float32))

tensor(5.)
tensor([4., 5., 6.])
tensor([2., 5., 8.])


In [20]:
# Product operation
print(pt.prod(X))
print(pt.prod(X, axis=0))
print(pt.prod(X, axis=1))

tensor(362880)
tensor([ 28,  80, 162])
tensor([  6, 120, 504])


## Dot Product

If we have two vectors (<strong>*x*</strong> and <strong>*y*</strong>) with the same length *n*, we can calculate the dot product between them. This is annotated several different ways, including the following:
- $x \cdot y$
- $x^T y$
- $\left< x,y\right>$

Regardless which notation you use, the calculation is the same; we calculate products in an element-wise fashion and then sum reductively across the products to a scalar value. That is, $x \cdot y = \sum^{n}_{i=1}x_{i}y_{i}$

The dot product is ubiquitous in deep learning: it is performed at every artificial neuron in a deep neural network, which may be made up of millions of these neurons.

In [21]:
# Vectors

vec1 = pt.tensor([1, 2, 3])
vec2 = pt.tensor([4, 5, 6])

print(vec1)
print(vec2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [22]:
# Dot product on vectors
pt.dot(vec1, vec2)

tensor(32)

---

## Exercises

1. What is $Y^T$
$$
Y = 
\left(\begin{array}{}
42 & 4 & 7 & 99\\
-99 & -3 & 17 & 22
\end{array}\right)
$$
2. What is the hadamard product of these matrices?
$$
\left(\begin{array}{}
25 & 10\\
-2 & 1
\end{array}\right)

\odot

\left(\begin{array}{}
-1 & 7\\
10 & 8
\end{array}\right)
$$
3. What is the dot product of the tensors ***w*** and ***x***

$$
w =
\left(\begin{array}{}
-1 & 2 & -2
\end{array}\right)
$$
$$
x =
\left(\begin{array}{}
5 & 10 & 0
\end{array}\right)
$$

In [23]:
# 1.- Transpose Y

Y = pt.tensor([[42, 4, 7, 99], [-99, -3 , 17, 22]]) # Matrix declaration
Y.T

tensor([[ 42, -99],
        [  4,  -3],
        [  7,  17],
        [ 99,  22]])

In [24]:
# 2.- Hadamard product

A = pt.tensor([[25, 10], [-2, 1]])
B = pt.tensor([[-1, 7], [10, 8]])

A * B

tensor([[-25,  70],
        [-20,   8]])

In [25]:
# 3.- Dot product

w = pt.tensor([-1, 2, -2])
x = pt.tensor([5, 10, 0])

pt.dot(w, x)

tensor(15)